// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace BattleArena.AcceptanceTests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CombatSystemFeature : object, global::Xunit.IClassFixture<CombatSystemFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en"), "Features", "Combat System", "    As a game designer\r\n    I want to resolve attacks and damage\r\n    So that com" +
                "bat follows the AD&D-inspired rules", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Combat.feature"
#line hidden
        
        public CombatSystemFeature(CombatSystemFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
    #line hidden
#line 7
        await testRunner.GivenAsync("a character with strength 14 and strike rating 19", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 8
        await testRunner.AndAsync("a weapon named \"Longsword\" with D8 damage die and +0 attack bonus", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Combat.feature.ndjson", 11);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Calculate ability modifier for various ability scores")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Combat System")]
        [global::Xunit.TraitAttribute("Description", "Calculate ability modifier for various ability scores")]
        [global::Xunit.TraitAttribute("Category", "ability")]
        public async global::System.Threading.Tasks.Task CalculateAbilityModifierForVariousAbilityScores()
        {
            string[] tagsOfScenario = new string[] {
                    "ability"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Calculate ability modifier for various ability scores", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 11
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
    await this.FeatureBackgroundAsync();
#line hidden
#line 12
        await testRunner.WhenAsync("the ability modifier is calculated for score 8", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 13
        await testRunner.ThenAsync("the modifier should be -1", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 14
        await testRunner.WhenAsync("the ability modifier is calculated for score 10", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 15
        await testRunner.ThenAsync("the modifier should be 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 16
        await testRunner.WhenAsync("the ability modifier is calculated for score 14", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 17
        await testRunner.ThenAsync("the modifier should be 2", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 18
        await testRunner.WhenAsync("the ability modifier is calculated for score 18", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 19
        await testRunner.ThenAsync("the modifier should be 4", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 20
        await testRunner.WhenAsync("the ability modifier is calculated for score 20", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 21
        await testRunner.ThenAsync("the modifier should be 5", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Successful melee attack hits and deals damage with strength bonus")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Combat System")]
        [global::Xunit.TraitAttribute("Description", "Successful melee attack hits and deals damage with strength bonus")]
        [global::Xunit.TraitAttribute("Category", "attack")]
        public async global::System.Threading.Tasks.Task SuccessfulMeleeAttackHitsAndDealsDamageWithStrengthBonus()
        {
            string[] tagsOfScenario = new string[] {
                    "attack"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Successful melee attack hits and deals damage with strength bonus", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 24
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
    await this.FeatureBackgroundAsync();
#line hidden
#line 25
        await testRunner.GivenAsync("the D20 roll is 12", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 26
        await testRunner.AndAsync("the damage die roll is 5", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 27
        await testRunner.WhenAsync("the character attacks a target with armor class 5", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 28
        await testRunner.ThenAsync("the attack should hit", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 29
        await testRunner.AndAsync("the hit roll should be 12", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 30
        await testRunner.AndAsync("the damage should be 7", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 31
        await testRunner.AndAsync("the weapon used should be \"Longsword\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Attack misses when roll is too low to beat the target armor class")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Combat System")]
        [global::Xunit.TraitAttribute("Description", "Attack misses when roll is too low to beat the target armor class")]
        [global::Xunit.TraitAttribute("Category", "attack")]
        public async global::System.Threading.Tasks.Task AttackMissesWhenRollIsTooLowToBeatTheTargetArmorClass()
        {
            string[] tagsOfScenario = new string[] {
                    "attack"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Attack misses when roll is too low to beat the target armor class", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 34
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
    await this.FeatureBackgroundAsync();
#line hidden
#line 35
        await testRunner.GivenAsync("the D20 roll is 5", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 36
        await testRunner.AndAsync("the damage die roll is 3", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 37
        await testRunner.WhenAsync("the character attacks a target with armor class 10", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 38
        await testRunner.ThenAsync("the attack should miss", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 39
        await testRunner.AndAsync("the damage should be 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Damage cannot go below zero even with a negative strength modifier")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Combat System")]
        [global::Xunit.TraitAttribute("Description", "Damage cannot go below zero even with a negative strength modifier")]
        [global::Xunit.TraitAttribute("Category", "attack")]
        public async global::System.Threading.Tasks.Task DamageCannotGoBelowZeroEvenWithANegativeStrengthModifier()
        {
            string[] tagsOfScenario = new string[] {
                    "attack"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Damage cannot go below zero even with a negative strength modifier", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 42
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
    await this.FeatureBackgroundAsync();
#line hidden
#line 43
        await testRunner.GivenAsync("a character with strength 6 and strike rating 19", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 44
        await testRunner.AndAsync("the D20 roll is 20", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 45
        await testRunner.AndAsync("the damage die roll is 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 46
        await testRunner.WhenAsync("the character attacks a target with armor class 5", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 47
        await testRunner.ThenAsync("the attack should hit", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 48
        await testRunner.AndAsync("the damage should be 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Lower strike rating makes attacks more likely to hit")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Combat System")]
        [global::Xunit.TraitAttribute("Description", "Lower strike rating makes attacks more likely to hit")]
        [global::Xunit.TraitAttribute("Category", "attack")]
        public async global::System.Threading.Tasks.Task LowerStrikeRatingMakesAttacksMoreLikelyToHit()
        {
            string[] tagsOfScenario = new string[] {
                    "attack"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Lower strike rating makes attacks more likely to hit", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 51
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
    await this.FeatureBackgroundAsync();
#line hidden
#line 52
        await testRunner.GivenAsync("a character with strength 16 and strike rating 15", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 53
        await testRunner.AndAsync("the D20 roll is 8", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 54
        await testRunner.AndAsync("the damage die roll is 6", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 55
        await testRunner.WhenAsync("the character attacks a target with armor class 5", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 56
        await testRunner.ThenAsync("the attack should hit", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 57
        await testRunner.AndAsync("the damage should be 9", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Weapon attack bonus improves hit chance")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Combat System")]
        [global::Xunit.TraitAttribute("Description", "Weapon attack bonus improves hit chance")]
        [global::Xunit.TraitAttribute("Category", "attack")]
        public async global::System.Threading.Tasks.Task WeaponAttackBonusImprovesHitChance()
        {
            string[] tagsOfScenario = new string[] {
                    "attack"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Weapon attack bonus improves hit chance", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 60
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
    await this.FeatureBackgroundAsync();
#line hidden
#line 61
        await testRunner.GivenAsync("a character with strength 10 and strike rating 19", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 62
        await testRunner.AndAsync("a weapon named \"Soul Reaver\" with D12 damage die and +3 attack bonus", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 63
        await testRunner.AndAsync("the D20 roll is 10", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 64
        await testRunner.AndAsync("the damage die roll is 7", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 65
        await testRunner.WhenAsync("the character attacks a target with armor class 5", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 66
        await testRunner.ThenAsync("the attack should hit", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 67
        await testRunner.AndAsync("the damage should be 7", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="High armor class makes attacks miss")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Combat System")]
        [global::Xunit.TraitAttribute("Description", "High armor class makes attacks miss")]
        [global::Xunit.TraitAttribute("Category", "attack")]
        public async global::System.Threading.Tasks.Task HighArmorClassMakesAttacksMiss()
        {
            string[] tagsOfScenario = new string[] {
                    "attack"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("High armor class makes attacks miss", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 70
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
    await this.FeatureBackgroundAsync();
#line hidden
#line 71
        await testRunner.GivenAsync("the D20 roll is 10", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 72
        await testRunner.AndAsync("the damage die roll is 4", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 73
        await testRunner.WhenAsync("the character attacks a target with armor class 15", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 74
        await testRunner.ThenAsync("the attack should miss", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 75
        await testRunner.AndAsync("the damage should be 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Roll damage for a weapon")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Combat System")]
        [global::Xunit.TraitAttribute("Description", "Roll damage for a weapon")]
        [global::Xunit.TraitAttribute("Category", "damage")]
        public async global::System.Threading.Tasks.Task RollDamageForAWeapon()
        {
            string[] tagsOfScenario = new string[] {
                    "damage"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Roll damage for a weapon", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 78
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
    await this.FeatureBackgroundAsync();
#line hidden
#line 79
        await testRunner.GivenAsync("the damage die roll is 7", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 80
        await testRunner.WhenAsync("the character rolls damage for the weapon", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 81
        await testRunner.ThenAsync("the damage result should be 7", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 82
        await testRunner.AndAsync("the damage die type should be D8", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Roll damage for a weapon with different die")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Combat System")]
        [global::Xunit.TraitAttribute("Description", "Roll damage for a weapon with different die")]
        [global::Xunit.TraitAttribute("Category", "damage")]
        public async global::System.Threading.Tasks.Task RollDamageForAWeaponWithDifferentDie()
        {
            string[] tagsOfScenario = new string[] {
                    "damage"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Roll damage for a weapon with different die", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 85
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
    await this.FeatureBackgroundAsync();
#line hidden
#line 86
        await testRunner.GivenAsync("a weapon named \"Dagger\" with D4 damage die and +0 attack bonus", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 87
        await testRunner.AndAsync("the damage die roll is 3", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 88
        await testRunner.WhenAsync("the character rolls damage for the weapon", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 89
        await testRunner.ThenAsync("the damage result should be 3", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 90
        await testRunner.AndAsync("the damage die type should be D4", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await CombatSystemFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await CombatSystemFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
