// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace BattleArena.AcceptanceTests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CombatAttackPowerAndDefensePowerDerivationFeature : object, global::Xunit.IClassFixture<CombatAttackPowerAndDefensePowerDerivationFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en"), "Features", "Combat — AttackPower and DefensePower Derivation", "    As a game designer\r\n    I want attack and defense power to aggregate all char" +
                "acter sources\r\n    So that every stat investment contributes meaningfully to com" +
                "bat", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "CombatStats.feature"
#line hidden
        
        public CombatAttackPowerAndDefensePowerDerivationFeature(CombatAttackPowerAndDefensePowerDerivationFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/CombatStats.feature.ndjson", 6);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Attack power aggregates class accuracy, level, strength, weapon, feats, and race")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Combat — AttackPower and DefensePower Derivation")]
        [global::Xunit.TraitAttribute("Description", "Attack power aggregates class accuracy, level, strength, weapon, feats, and race")]
        [global::Xunit.TraitAttribute("Category", "combat-stats")]
        public async global::System.Threading.Tasks.Task AttackPowerAggregatesClassAccuracyLevelStrengthWeaponFeatsAndRace()
        {
            string[] tagsOfScenario = new string[] {
                    "combat-stats"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Attack power aggregates class accuracy, level, strength, weapon, feats, and race", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 36
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 37
        await testRunner.GivenAsync("an attacker at level 3 with strength 16 and strike rating 17", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 38
        await testRunner.AndAsync("the attacker has a combat feat granting +2 attack bonus", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 39
        await testRunner.AndAsync("the attacker\'s race has a combat feat granting +1 attack bonus", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 40
        await testRunner.AndAsync("the attacker uses a melee weapon with attack bonus 2", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 41
        await testRunner.WhenAsync("attack power is computed", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 42
        await testRunner.ThenAsync("the total attack power should be 14", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Buff stacking rules are applied correctly to attack power")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Combat — AttackPower and DefensePower Derivation")]
        [global::Xunit.TraitAttribute("Description", "Buff stacking rules are applied correctly to attack power")]
        [global::Xunit.TraitAttribute("Category", "combat-stats")]
        public async global::System.Threading.Tasks.Task BuffStackingRulesAreAppliedCorrectlyToAttackPower()
        {
            string[] tagsOfScenario = new string[] {
                    "combat-stats"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Buff stacking rules are applied correctly to attack power", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 53
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 54
        await testRunner.GivenAsync("an attacker at level 1 with strength 10 and strike rating 20", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 55
        await testRunner.AndAsync("the attacker uses a melee weapon with attack bonus 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 56
        await testRunner.AndAsync("the attacker has a stacking attack buff with +3 modifier", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 57
        await testRunner.AndAsync("the attacker has a highest-wins attack buff with +4 modifier", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 58
        await testRunner.AndAsync("the attacker has a highest-wins attack buff with +2 modifier", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 59
        await testRunner.AndAsync("the attacker has an attack debuff with -2 modifier", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 60
        await testRunner.WhenAsync("attack power is computed", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 62
        await testRunner.ThenAsync("the total attack power should be 6", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Defense power converts raw armor class to effective armor class")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Combat — AttackPower and DefensePower Derivation")]
        [global::Xunit.TraitAttribute("Description", "Defense power converts raw armor class to effective armor class")]
        [global::Xunit.TraitAttribute("Category", "combat-stats")]
        public async global::System.Threading.Tasks.Task DefensePowerConvertsRawArmorClassToEffectiveArmorClass()
        {
            string[] tagsOfScenario = new string[] {
                    "combat-stats"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Defense power converts raw armor class to effective armor class", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 67
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 68
        await testRunner.GivenAsync("a stats defender with dexterity 10", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 69
        await testRunner.AndAsync("the stats defender wears chest armor with class 5 and max dex bonus 10", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 70
        await testRunner.WhenAsync("defense power is computed", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 72
        await testRunner.ThenAsync("the total defense power should be 15", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Dexterity bonus is capped by the most restrictive armor piece")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Combat — AttackPower and DefensePower Derivation")]
        [global::Xunit.TraitAttribute("Description", "Dexterity bonus is capped by the most restrictive armor piece")]
        [global::Xunit.TraitAttribute("Category", "combat-stats")]
        public async global::System.Threading.Tasks.Task DexterityBonusIsCappedByTheMostRestrictiveArmorPiece()
        {
            string[] tagsOfScenario = new string[] {
                    "combat-stats"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Dexterity bonus is capped by the most restrictive armor piece", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 80
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 81
        await testRunner.GivenAsync("a stats defender with dexterity 18", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 82
        await testRunner.AndAsync("the stats defender wears chest armor with class 6 and max dex bonus 2", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 83
        await testRunner.AndAsync("the stats defender wears head armor with class 2 and max dex bonus 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 84
        await testRunner.AndAsync("the stats defender carries a shield with +3 defense bonus", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 85
        await testRunner.WhenAsync("defense power is computed", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 86
        await testRunner.ThenAsync("the computed effective armor class should be 12", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 87
        await testRunner.AndAsync("the computed dexterity modifier should be 3", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 88
        await testRunner.AndAsync("the total defense power should be 18", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await CombatAttackPowerAndDefensePowerDerivationFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await CombatAttackPowerAndDefensePowerDerivationFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
