// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace BattleArena.AcceptanceTests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CombatDamageFormulaFeature : object, global::Xunit.IClassFixture<CombatDamageFormulaFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en"), "Features", "Combat — Damage Formula", "    As a game designer\r\n    I want damage to reflect weapon dice, attributes, vul" +
                "nerabilities, mitigation, and elemental bonuses\r\n    So that item choices and ch" +
                "aracter builds have meaningful impact", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "DamageFormula.feature"
#line hidden
        
        public CombatDamageFormulaFeature(CombatDamageFormulaFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 19
    #line hidden
#line 20
        await testRunner.GivenAsync("a damage formula attacker with strength 14", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 21
        await testRunner.AndAsync("a Slashing damage weapon with D8 die", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/DamageFormula.feature.ndjson", 9);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Standard damage applies weapon dice and attribute modifier")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Combat — Damage Formula")]
        [global::Xunit.TraitAttribute("Description", "Standard damage applies weapon dice and attribute modifier")]
        [global::Xunit.TraitAttribute("Category", "damage-formula")]
        public async global::System.Threading.Tasks.Task StandardDamageAppliesWeaponDiceAndAttributeModifier()
        {
            string[] tagsOfScenario = new string[] {
                    "damage-formula"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Standard damage applies weapon dice and attribute modifier", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 26
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 19
    await this.FeatureBackgroundAsync();
#line hidden
#line 27
        await testRunner.AndAsync("a damage formula target with no modifiers", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 28
        await testRunner.AndAsync("the weapon damage die rolls 5", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 29
        await testRunner.WhenAsync("damage is resolved against the target", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 30
        await testRunner.ThenAsync("the base damage should be 7", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 31
        await testRunner.AndAsync("the final damage should be 7", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Flat weapon damage bonus increases base damage")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Combat — Damage Formula")]
        [global::Xunit.TraitAttribute("Description", "Flat weapon damage bonus increases base damage")]
        [global::Xunit.TraitAttribute("Category", "damage-formula")]
        public async global::System.Threading.Tasks.Task FlatWeaponDamageBonusIncreasesBaseDamage()
        {
            string[] tagsOfScenario = new string[] {
                    "damage-formula"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Flat weapon damage bonus increases base damage", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 36
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 19
    await this.FeatureBackgroundAsync();
#line hidden
#line 37
        await testRunner.AndAsync("a damage formula target with no modifiers", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 38
        await testRunner.AndAsync("the weapon has a flat damage bonus of 2", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 39
        await testRunner.AndAsync("the weapon damage die rolls 5", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 40
        await testRunner.WhenAsync("damage is resolved against the target", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 41
        await testRunner.ThenAsync("the base damage should be 9", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 42
        await testRunner.AndAsync("the final damage should be 9", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Elemental damage bonus is added after armor mitigation")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Combat — Damage Formula")]
        [global::Xunit.TraitAttribute("Description", "Elemental damage bonus is added after armor mitigation")]
        [global::Xunit.TraitAttribute("Category", "damage-formula")]
        public async global::System.Threading.Tasks.Task ElementalDamageBonusIsAddedAfterArmorMitigation()
        {
            string[] tagsOfScenario = new string[] {
                    "damage-formula"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Elemental damage bonus is added after armor mitigation", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 47
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 19
    await this.FeatureBackgroundAsync();
#line hidden
#line 48
        await testRunner.AndAsync("a damage formula target with no modifiers", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 49
        await testRunner.AndAsync("the weapon deals 3 elemental bonus damage", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 50
        await testRunner.AndAsync("the weapon damage die rolls 5", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 51
        await testRunner.WhenAsync("damage is resolved against the target", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 52
        await testRunner.ThenAsync("the final damage should be 10", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Armor mitigation reduces final damage")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Combat — Damage Formula")]
        [global::Xunit.TraitAttribute("Description", "Armor mitigation reduces final damage")]
        [global::Xunit.TraitAttribute("Category", "damage-formula")]
        public async global::System.Threading.Tasks.Task ArmorMitigationReducesFinalDamage()
        {
            string[] tagsOfScenario = new string[] {
                    "damage-formula"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Armor mitigation reduces final damage", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 57
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 19
    await this.FeatureBackgroundAsync();
#line hidden
#line 58
        await testRunner.AndAsync("a damage formula target with armor mitigation of 3", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 59
        await testRunner.AndAsync("the weapon damage die rolls 5", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 60
        await testRunner.WhenAsync("damage is resolved against the target", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 61
        await testRunner.ThenAsync("the final damage should be 4", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Final damage cannot fall below zero when mitigation exceeds base damage")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Combat — Damage Formula")]
        [global::Xunit.TraitAttribute("Description", "Final damage cannot fall below zero when mitigation exceeds base damage")]
        [global::Xunit.TraitAttribute("Category", "damage-formula")]
        public async global::System.Threading.Tasks.Task FinalDamageCannotFallBelowZeroWhenMitigationExceedsBaseDamage()
        {
            string[] tagsOfScenario = new string[] {
                    "damage-formula"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Final damage cannot fall below zero when mitigation exceeds base damage", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 66
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 19
    await this.FeatureBackgroundAsync();
#line hidden
#line 67
        await testRunner.GivenAsync("a damage formula attacker with strength 10", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 68
        await testRunner.AndAsync("a Slashing damage weapon with D4 die", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 69
        await testRunner.AndAsync("a damage formula target with armor mitigation of 5", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 70
        await testRunner.AndAsync("the weapon damage die rolls 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 71
        await testRunner.WhenAsync("damage is resolved against the target", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 72
        await testRunner.ThenAsync("the final damage should be 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Defender vulnerability multiplies base damage by one point five")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Combat — Damage Formula")]
        [global::Xunit.TraitAttribute("Description", "Defender vulnerability multiplies base damage by one point five")]
        [global::Xunit.TraitAttribute("Category", "damage-formula")]
        public async global::System.Threading.Tasks.Task DefenderVulnerabilityMultipliesBaseDamageByOnePointFive()
        {
            string[] tagsOfScenario = new string[] {
                    "damage-formula"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Defender vulnerability multiplies base damage by one point five", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 77
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 19
    await this.FeatureBackgroundAsync();
#line hidden
#line 78
        await testRunner.AndAsync("a damage formula target with no modifiers", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 79
        await testRunner.AndAsync("the target is vulnerable to Slashing damage", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 80
        await testRunner.AndAsync("the weapon damage die rolls 6", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 81
        await testRunner.WhenAsync("damage is resolved against the target", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 82
        await testRunner.ThenAsync("the base damage should be 8", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 83
        await testRunner.AndAsync("the final damage should be 12", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="All damage modifiers combine correctly in the full pipeline")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Combat — Damage Formula")]
        [global::Xunit.TraitAttribute("Description", "All damage modifiers combine correctly in the full pipeline")]
        [global::Xunit.TraitAttribute("Category", "damage-formula")]
        public async global::System.Threading.Tasks.Task AllDamageModifiersCombineCorrectlyInTheFullPipeline()
        {
            string[] tagsOfScenario = new string[] {
                    "damage-formula"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("All damage modifiers combine correctly in the full pipeline", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 91
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 19
    await this.FeatureBackgroundAsync();
#line hidden
#line 92
        await testRunner.AndAsync("the weapon has a flat damage bonus of 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 93
        await testRunner.AndAsync("the weapon deals 3 elemental bonus damage", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 94
        await testRunner.AndAsync("a damage formula target with armor mitigation of 2", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 95
        await testRunner.AndAsync("the target is vulnerable to Slashing damage", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 96
        await testRunner.AndAsync("the weapon damage die rolls 5", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 97
        await testRunner.WhenAsync("damage is resolved against the target", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 98
        await testRunner.ThenAsync("the base damage should be 8", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 99
        await testRunner.AndAsync("the final damage should be 13", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await CombatDamageFormulaFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await CombatDamageFormulaFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
