// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace BattleArena.AcceptanceTests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CombatStatusEffectsFeature : object, global::Xunit.IClassFixture<CombatStatusEffectsFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en"), "Features", "Combat — Status Effects", "    As a game designer\r\n    I want status effects to stack, replace, or block bas" +
                "ed on defined rules\r\n    So that buff and debuff interactions are predictable an" +
                "d exploitable", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "StatusEffects.feature"
#line hidden
        
        public CombatStatusEffectsFeature(CombatStatusEffectsFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/StatusEffects.feature.ndjson", 8);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="NoStack prevents a second application of the same effect")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Combat — Status Effects")]
        [global::Xunit.TraitAttribute("Description", "NoStack prevents a second application of the same effect")]
        [global::Xunit.TraitAttribute("Category", "status-effects")]
        public async global::System.Threading.Tasks.Task NoStackPreventsASecondApplicationOfTheSameEffect()
        {
            string[] tagsOfScenario = new string[] {
                    "status-effects"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("NoStack prevents a second application of the same effect", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 23
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 24
        await testRunner.GivenAsync("a fresh character with no status effects", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 26
        await testRunner.WhenAsync("the effect \"Bless\" with NoStack rule and magnitude 3 from \"priest\" is applied", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 28
        await testRunner.AndAsync("the effect \"Bless\" with NoStack rule and magnitude 3 from \"priest\" is applied", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 29
        await testRunner.ThenAsync("the character should have 1 active status effect", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="HighestWins replaces a weaker instance with a stronger one")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Combat — Status Effects")]
        [global::Xunit.TraitAttribute("Description", "HighestWins replaces a weaker instance with a stronger one")]
        [global::Xunit.TraitAttribute("Category", "status-effects")]
        public async global::System.Threading.Tasks.Task HighestWinsReplacesAWeakerInstanceWithAStrongerOne()
        {
            string[] tagsOfScenario = new string[] {
                    "status-effects"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("HighestWins replaces a weaker instance with a stronger one", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 34
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 35
        await testRunner.GivenAsync("a fresh character with no status effects", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 37
        await testRunner.WhenAsync("the effect \"Shield\" with HighestWins rule and magnitude 2 from \"spell-a\" is appli" +
                        "ed", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 39
        await testRunner.AndAsync("the effect \"Shield\" with HighestWins rule and magnitude 5 from \"spell-b\" is appli" +
                        "ed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 40
        await testRunner.ThenAsync("the character should have 1 active status effect", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 41
        await testRunner.AndAsync("the active effect \"Shield\" should have magnitude 5", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="HighestWins keeps the existing effect when the new one is weaker")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Combat — Status Effects")]
        [global::Xunit.TraitAttribute("Description", "HighestWins keeps the existing effect when the new one is weaker")]
        [global::Xunit.TraitAttribute("Category", "status-effects")]
        public async global::System.Threading.Tasks.Task HighestWinsKeepsTheExistingEffectWhenTheNewOneIsWeaker()
        {
            string[] tagsOfScenario = new string[] {
                    "status-effects"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("HighestWins keeps the existing effect when the new one is weaker", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 46
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 47
        await testRunner.GivenAsync("a fresh character with no status effects", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 48
        await testRunner.WhenAsync("the effect \"Shield\" with HighestWins rule and magnitude 5 from \"spell-a\" is appli" +
                        "ed", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 49
        await testRunner.AndAsync("the effect \"Shield\" with HighestWins rule and magnitude 2 from \"spell-b\" is appli" +
                        "ed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 50
        await testRunner.ThenAsync("the character should have 1 active status effect", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 51
        await testRunner.AndAsync("the active effect \"Shield\" should have magnitude 5", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Stack allows the same effect from different sources but blocks the same source")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Combat — Status Effects")]
        [global::Xunit.TraitAttribute("Description", "Stack allows the same effect from different sources but blocks the same source")]
        [global::Xunit.TraitAttribute("Category", "status-effects")]
        public async global::System.Threading.Tasks.Task StackAllowsTheSameEffectFromDifferentSourcesButBlocksTheSameSource()
        {
            string[] tagsOfScenario = new string[] {
                    "status-effects"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Stack allows the same effect from different sources but blocks the same source", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 57
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 58
        await testRunner.GivenAsync("a fresh character with no status effects", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 60
        await testRunner.WhenAsync("the effect \"Bleed\" with Stack rule and magnitude 1 from \"enemy-a\" is applied", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 62
        await testRunner.AndAsync("the effect \"Bleed\" with Stack rule and magnitude 1 from \"enemy-a\" is applied", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 64
        await testRunner.AndAsync("the effect \"Bleed\" with Stack rule and magnitude 1 from \"enemy-b\" is applied", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 65
        await testRunner.ThenAsync("the character should have 2 active status effects", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Effects expire when their duration reaches zero after ticking")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Combat — Status Effects")]
        [global::Xunit.TraitAttribute("Description", "Effects expire when their duration reaches zero after ticking")]
        [global::Xunit.TraitAttribute("Category", "status-effects")]
        public async global::System.Threading.Tasks.Task EffectsExpireWhenTheirDurationReachesZeroAfterTicking()
        {
            string[] tagsOfScenario = new string[] {
                    "status-effects"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Effects expire when their duration reaches zero after ticking", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 71
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 72
        await testRunner.GivenAsync("a fresh character with active effect \"Haste\" lasting 2 turns", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 73
        await testRunner.AndAsync("the character also has active effect \"Burn\" lasting 1 turn", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 75
        await testRunner.WhenAsync("status effects tick once", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 76
        await testRunner.ThenAsync("the character should have 1 active status effect", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 77
        await testRunner.AndAsync("the active effect \"Haste\" should have 1 turn remaining", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 78
        await testRunner.AndAsync("the active effect \"Burn\" should have expired", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Permanent effects with duration zero are never removed by ticking")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Combat — Status Effects")]
        [global::Xunit.TraitAttribute("Description", "Permanent effects with duration zero are never removed by ticking")]
        [global::Xunit.TraitAttribute("Category", "status-effects")]
        public async global::System.Threading.Tasks.Task PermanentEffectsWithDurationZeroAreNeverRemovedByTicking()
        {
            string[] tagsOfScenario = new string[] {
                    "status-effects"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Permanent effects with duration zero are never removed by ticking", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 83
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 84
        await testRunner.GivenAsync("a fresh character with active effect \"Aura\" lasting 0 turns", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 86
        await testRunner.WhenAsync("status effects tick once", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 87
        await testRunner.AndAsync("status effects tick once", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 88
        await testRunner.AndAsync("status effects tick once", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 89
        await testRunner.ThenAsync("the character should have 1 active status effect", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 90
        await testRunner.AndAsync("the active effect \"Aura\" should have 0 turns remaining", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await CombatStatusEffectsFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await CombatStatusEffectsFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
