namespace BattleArena.Application.Services;

using Core.Entities;
using Models;

// XP rewards and level-up logic for battles.
// XP is awarded to each surviving party member after a battle based on:
//   - base value from enemy levels (difficulty)
//   - bonus per critical hit landed by the party
//   - penalty per fumble by the party
//   - round factor: fights that are very quick (efficient) or very long (grueling)
//     earn a multiplier bonus; standard-length fights earn base XP.
// Level thresholds, strike rating bonuses, and accessory slot unlocks are defined in LevelProgression.
public class LevelingService
{
    private const int XpMultiplier = 12;
    private const int CritBonus = 8;
    private const int FumblePenalty = 8;
    private const double RoundFactorK = 0.3;
    private const double RoundFactorMin = 0.5;
    private const double RoundFactorMax = 2.0;

    // Returns the total XP pool generated by a battle, factoring in difficulty,
    // critical hits, fumbles, and battle duration.
    public int ComputeBattleXp(
        IEnumerable<Character> party,
        IEnumerable<Character> enemies,
        IReadOnlyCollection<BattleLogEntry> log,
        int totalTicks)
    {
        var baseXp = enemies.Sum(e => e.Level) * XpMultiplier;
        var partyNames = party.Select(c => c.Name).ToHashSet();

        var partyCrits = log.Count(e =>
            e.EventType == "Attack" && e.IsCritical == true && partyNames.Contains(e.ActorName));
        var partyFumbles = log.Count(e =>
            e.EventType == "Attack" && e.IsFumble == true && partyNames.Contains(e.ActorName));

        var expectedRounds = Math.Max(1, (party.Count() + enemies.Count()) * 2);
        var ratio = (double)totalTicks / expectedRounds;
        var roundFactor = 1.0 + Math.Abs(ratio - 1.0) * RoundFactorK;
        roundFactor = Math.Clamp(roundFactor, RoundFactorMin, RoundFactorMax);

        var totalXp = (int)(baseXp * roundFactor) + (partyCrits - partyFumbles) * CritBonus;
        return Math.Max(0, totalXp);
    }

    // Splits XP among survivors (rounds down). Dead/KO'd members get nothing.
    public IReadOnlyDictionary<string, int> AwardBattleXp(
        IEnumerable<Character> party,
        IEnumerable<Character> enemies,
        IReadOnlyCollection<BattleLogEntry> log,
        int totalTicks)
    {
        var totalXp = ComputeBattleXp(party, enemies, log, totalTicks);
        var survivors = party.Where(c => c.IsAlive).ToList();
        if (survivors.Count == 0)
            return new Dictionary<string, int>();

        var share = totalXp / survivors.Count;
        var result = new Dictionary<string, int>();
        foreach (var c in survivors)
        {
            c.ExperiencePoints += share;
            c.Level = LevelProgression.LevelFromXp(c.ExperiencePoints);
            result[c.Name] = share;
        }
        return result;
    }

    // Effective strike rating after level-based reductions.
    public int EffectiveStrikeRating(Character character)
    {
        var archetype = LevelProgression.Archetype(character.ClassId);
        var bonus = LevelProgression.SrBonus(character.Level, archetype);
        return Math.Max(1, character.StrikeRating - bonus);
    }

    // Number of accessory slots available at the character's current level and class.
    public int AccessorySlotCount(Character character)
    {
        var archetype = LevelProgression.Archetype(character.ClassId);
        return LevelProgression.AccessorySlots(character.Level, archetype);
    }

    // Describes the level-up delta, if any.
    public LevelUpResult? CheckLevelUp(Character before, Character after)
    {
        if (after.Level <= before.Level) return null;
        return new LevelUpResult
        {
            OldLevel = before.Level,
            NewLevel = after.Level,
            StrikeRatingImproved = EffectiveStrikeRating(after) < EffectiveStrikeRating(before),
            NewAccessorySlots = AccessorySlotCount(after)
        };
    }
}

public class LevelUpResult
{
    public int OldLevel { get; init; }
    public int NewLevel { get; init; }
    public bool StrikeRatingImproved { get; init; }
    public int NewAccessorySlots { get; init; }
}
